version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: The uncompromising code formatter check
          command: |
            pip install black==20.8b1
            black mylearn -l 120 --check
      - run:
          name: Pytest code testing
          command: |
            pip install pytest==6.2.3
            pytest tests

workflows:
  main:
    jobs:
      - build-and-test